<?php

if(!class_exists('HT_Social_Widget_Defaults')){
	class HT_Social_Widget_Defaults {

		/**
		* Get the social media default items
		*/
		public static function get_social_media_defaults(){
			$defaults = array(

				0 => array( 'provider_id' => 'fivehundredpx',
								'enabled' => false,
								'name' => __('500px', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	0, 
							),

				1 => array( 'provider_id' => 'aboutme',
								'enabled' => false,
								'name' => __('About Me', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	1, 
							),

				2 => array( 'provider_id' => 'addme',
								'enabled' => false,
								'name' => __('Add Me', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	2, 
							),

				3 => array( 'provider_id' => 'amazon',
								'enabled' => false,
								'name' => __('amazon', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	3, 
							),

				4 => array( 'provider_id' => 'aol',
								'enabled' => false,
								'name' => __('AOL', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	4, 
							),

				5 => array( 'provider_id' => 'appstorealt',
								'enabled' => false,
								'name' => __('App Store Alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	5, 
							),

				6 => array( 'provider_id' => 'appstore',
								'enabled' => false,
								'name' => __('App Store', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	6, 
							),

				7 => array( 'provider_id' => 'apple',
								'enabled' => false,
								'name' => __('Apple', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	7, 
							),

				8 => array( 'provider_id' => 'bebo',
								'enabled' => false,
								'name' => __('Bebo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	8, 
							),

				9 => array( 'provider_id' => 'behance',
								'enabled' => false,
								'name' => __('Behance', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	9, 
							),

				10 => array( 'provider_id' => 'bing',
								'enabled' => false,
								'name' => __('bing', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 10, 
							),

				11 => array( 'provider_id' => 'blip',
								'enabled' => false,
								'name' => __('blip', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 11, 
							),

				12 => array( 'provider_id' => 'blogger',
								'enabled' => false,
								'name' => __('Blogger', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 12, 
							),

				13 => array( 'provider_id' => 'coroflot',
								'enabled' => false,
								'name' => __('coroflot', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 13, 
							),

				14 => array( 'provider_id' => 'daytum',
								'enabled' => false,
								'name' => __('daytum', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 14, 
							),

				15 => array( 'provider_id' => 'delicious',
								'enabled' => false,
								'name' => __('delicious', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 15, 
							),

				16 => array( 'provider_id' => 'designbump',
								'enabled' => false,
								'name' => __('Design Bump', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 16, 
							),

				17 => array( 'provider_id' => 'designfloat',
								'enabled' => false,
								'name' => __('Design Float', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 17, 
							),

				18 => array( 'provider_id' => 'deviantart',
								'enabled' => false,
								'name' => __('Deviantart', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#4e6252',
								'url' => '',
								'order' => 18, 
							),

				19 => array( 'provider_id' => 'diggalt',
								'enabled' => false,
								'name' => __('Digg Alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 19, 
							),

				20 => array( 'provider_id' => 'digg',
								'enabled' => false,
								'name' => __('Digg', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 20, 
							),

				21 => array( 'provider_id' => 'dribble',
								'enabled' => false,
								'name' => __('Dribble', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#ea4c89',
								'url' => '',
								'order' => 21, 
							),

				22 => array( 'provider_id' => 'drupal',
								'enabled' => false,
								'name' => __('Drupal', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 22, 
							),

				23 => array( 'provider_id' => 'ebay',
								'enabled' => false,
								'name' => __('eBay', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 23, 
							),

				24 => array( 'provider_id' => 'email',
								'enabled' => false,
								'name' => __('eMail', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 24, 
							),

				25 => array( 'provider_id' => 'emberapp',
								'enabled' => false,
								'name' => __('Ember', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 25, 
							),

				26 => array( 'provider_id' => 'etsy',
								'enabled' => false,
								'name' => __('etsy', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 26, 
							),

				27 => array( 'provider_id' => 'facebook',
								'enabled' => false,
								'name' => __('Facebook', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#3b5998',
								'url' => '',
								'order' => 27, 
							),

				28 => array( 'provider_id' => 'feedburner',
								'enabled' => false,
								'name' => __('Feed Burner', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 28, 
							),

				29 => array( 'provider_id' => 'flickr',
								'enabled' => false,
								'name' => __('flickr', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#ff0084',
								'url' => '',
								'order' => 29, 
							),

				30 => array( 'provider_id' => 'foodspotting',
								'enabled' => false,
								'name' => __('Food Spotting', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 30, 
							),

				31 => array( 'provider_id' => 'forrst',
								'enabled' => false,
								'name' => __('forrst', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 31, 
							),

				32 => array( 'provider_id' => 'foursquare',
								'enabled' => false,
								'name' => __('Four Square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0072b1',
								'url' => '',
								'order' => 32, 
							),

				33 => array( 'provider_id' => 'friendsfeed',
								'enabled' => false,
								'name' => __('Friends Feed', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 33, 
							),

				34 => array( 'provider_id' => 'friendstar',
								'enabled' => false,
								'name' => __('Friend Star', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 34, 
							),

				35 => array( 'provider_id' => 'gdgt',
								'enabled' => false,
								'name' => __('GDGT', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 35, 
							),

				36 => array( 'provider_id' => 'github',
								'enabled' => false,
								'name' => __('Git Hub', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 36, 
							),

				37 => array( 'provider_id' => 'githubalt',
								'enabled' => false,
								'name' => __('Git Hub alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 37, 
							),

				38 => array( 'provider_id' => 'googlebuzz',
								'enabled' => false,
								'name' => __('Google Buzz', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 38, 
							),

				39 => array( 'provider_id' => 'googleplus',
								'enabled' => false,
								'name' => __('Google Plus', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 39, 
							),

				40 => array( 'provider_id' => 'googletalk',
								'enabled' => false,
								'name' => __('Google Talk', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 40, 
							),

				41 => array( 'provider_id' => 'gowallapin',
								'enabled' => false,
								'name' => __('Gowalla Pin', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 41, 
							),

				42 => array( 'provider_id' => 'gowalla',
								'enabled' => false,
								'name' => __('Gowalla', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 42, 
							),

				43 => array( 'provider_id' => 'grooveshark',
								'enabled' => false,
								'name' => __('Groove Shark', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 43, 
							),

				44 => array( 'provider_id' => 'heart',
								'enabled' => false,
								'name' => __('Heart', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 44, 
							),

				45 => array( 'provider_id' => 'hyves',
								'enabled' => false,
								'name' => __('hyves', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 45, 
							),

				46 => array( 'provider_id' => 'icondock',
								'enabled' => false,
								'name' => __('Icon Dock', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 46, 
							),

				47 => array( 'provider_id' => 'icq',
								'enabled' => false,
								'name' => __('ICQ', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 47, 
							),

				48 => array( 'provider_id' => 'identica',
								'enabled' => false,
								'name' => __('identica', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 48, 
							),

				49 => array( 'provider_id' => 'imessage',
								'enabled' => false,
								'name' => __('iMessage', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 49, 
							),

				50 => array( 'provider_id' => 'instagram',
								'enabled' => false,
								'name' => __('instagram', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#517fa4',
								'url' => '',
								'order' => 50, 
							),

				51 => array( 'provider_id' => 'itunes',
								'enabled' => false,
								'name' => __('iTunes', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 51, 
							),

				52 => array( 'provider_id' => 'lastfm',
								'enabled' => false,
								'name' => __('LastFM', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 52, 
							),

				53 => array( 'provider_id' => 'linkedin',
								'enabled' => false,
								'name' => __('LinkedIn', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#007bb6',
								'url' => '',
								'order' => 53, 
							),

				54 => array( 'provider_id' => 'meetup',
								'enabled' => false,
								'name' => __('Meetup', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 54, 
							),

				55 => array( 'provider_id' => 'metacafe',
								'enabled' => false,
								'name' => __('Metacafe', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 55, 
							),

				56 => array( 'provider_id' => 'mixx',
								'enabled' => false,
								'name' => __('Mixx', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 56, 
							),

				57 => array( 'provider_id' => 'mobileme',
								'enabled' => false,
								'name' => __('Mobile |Me', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 57, 
							),

				58 => array( 'provider_id' => 'mrwong',
								'enabled' => false,
								'name' => __('MrWong', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 58, 
							),

				59 => array( 'provider_id' => 'msn',
								'enabled' => false,
								'name' => __('MSN', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 59, 
							),

				60 => array( 'provider_id' => 'myspace',
								'enabled' => false,
								'name' => __('MySpace', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 60, 
							),

				61 => array( 'provider_id' => 'newsvine',
								'enabled' => false,
								'name' => __('Newsvine', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 61, 
							),

				62 => array( 'provider_id' => 'paypal',
								'enabled' => false,
								'name' => __('PayPal', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 62, 
							),

				63 => array( 'provider_id' => 'photobucket',
								'enabled' => false,
								'name' => __('Photo Bucket', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 63, 
							),

				64 => array( 'provider_id' => 'picasa',
								'enabled' => false,
								'name' => __('Picasa', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 64, 
							),

				65 => array( 'provider_id' => 'pinterest',
								'enabled' => false,
								'name' => __('Pinterest', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#cb2027',
								'url' => '',
								'order' => 65, 
							),

				66 => array( 'provider_id' => 'podcast',
								'enabled' => false,
								'name' => __('Podcast', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 66, 
							),

				67 => array( 'provider_id' => 'posterous',
								'enabled' => false,
								'name' => __('Posterous', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 67, 
							),

				68 => array( 'provider_id' => 'qik',
								'enabled' => false,
								'name' => __('Qik', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 68, 
							),

				69 => array( 'provider_id' => 'quora',
								'enabled' => false,
								'name' => __('Quora', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#a82400',
								'url' => '',
								'order' => 69, 
							),

				70 => array( 'provider_id' => 'reddit',
								'enabled' => false,
								'name' => __('Reddit', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 70, 
							),

				71 => array( 'provider_id' => 'retweet',
								'enabled' => false,
								'name' => __('Retweet', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 71, 
							),

				72 => array( 'provider_id' => 'rss',
								'enabled' => false,
								'name' => __('RSS', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 72, 
							),

				73 => array( 'provider_id' => 'scribd',
								'enabled' => false,
								'name' => __('Scribd', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 73, 
							),

				74 => array( 'provider_id' => 'sharethis',
								'enabled' => false,
								'name' => __('Share This', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 74, 
							),

				75 => array( 'provider_id' => 'skype',
								'enabled' => false,
								'name' => __('Skype', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 75, 
							),

				76 => array( 'provider_id' => 'slashdot',
								'enabled' => false,
								'name' => __('Slashdot', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 76, 
							),

				77 => array( 'provider_id' => 'slideshare',
								'enabled' => false,
								'name' => __('Slideshare', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 77, 
							),

				78 => array( 'provider_id' => 'smugmug',
								'enabled' => false,
								'name' => __('Smug Mug', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 78, 
							),

				79 => array( 'provider_id' => 'soundcloud',
								'enabled' => false,
								'name' => __('Sound Cloud', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 79, 
							),

				80 => array( 'provider_id' => 'spotify',
								'enabled' => false,
								'name' => __('Spotify', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 80, 
							),

				81 => array( 'provider_id' => 'squidoo',
								'enabled' => false,
								'name' => __('Squidoo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 81, 
							),

				82 => array( 'provider_id' => 'stackoverflow',
								'enabled' => false,
								'name' => __('Stack Overflow', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 82, 
							),

				83 => array( 'provider_id' => 'star',
								'enabled' => false,
								'name' => __('Star', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 83, 
							),

				84 => array( 'provider_id' => 'stumbleupon',
								'enabled' => false,
								'name' => __('Stumble Upon', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 84, 
							),

				85 => array( 'provider_id' => 'technorati',
								'enabled' => false,
								'name' => __('Technorati', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 85, 
							),

				86 => array( 'provider_id' => 'tumblr',
								'enabled' => false,
								'name' => __('Tumblr', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#32506d',
								'url' => '',
								'order' => 86, 
							),

				87 => array( 'provider_id' => 'twitterbird',
								'enabled' => false,
								'name' => __('Twitter', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#00aced',
								'url' => '',
								'order' => 87, 
							),

				88 => array( 'provider_id' => 'twitter',
								'enabled' => false,
								'name' => __('Twitter', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#00aced',
								'url' => '',
								'order' => 88, 
							),

				89 => array( 'provider_id' => 'viddler',
								'enabled' => false,
								'name' => __('Viddler', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 89, 
							),

				90 => array( 'provider_id' => 'vimeo',
								'enabled' => false,
								'name' => __('Vimeo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#aad450',
								'url' => '',
								'order' => 90, 
							),

				91 => array( 'provider_id' => 'virb',
								'enabled' => false,
								'name' => __('virb', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 91, 
							),

				92 => array( 'provider_id' => 'www',
								'enabled' => false,
								'name' => __('Website', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 92, 
							),

				93 => array( 'provider_id' => 'wikipedia',
								'enabled' => false,
								'name' => __('Wikipedia', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 93, 
							),

				94 => array( 'provider_id' => 'windows',
								'enabled' => false,
								'name' => __('Windows', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 94, 
							),

				95 => array( 'provider_id' => 'wordpress',
								'enabled' => false,
								'name' => __('WordPress', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 95, 
							),

				96 => array( 'provider_id' => 'xing',
								'enabled' => false,
								'name' => __('xing', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 96, 
							),

				97 => array( 'provider_id' => 'yahoobuzz',
								'enabled' => false,
								'name' => __('Yahoo Buzz', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#720e9e',
								'url' => '',
								'order' => 97, 
							),

				98 => array( 'provider_id' => 'yahoo',
								'enabled' => false,
								'name' => __('Yahoo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#720e9e',
								'url' => '',
								'order' => 98, 
							),

				99 => array( 'provider_id' => 'yelp',
								'enabled' => false,
								'name' => __('Yelp', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 99, 
							),

				100 => array( 'provider_id' => 'youtube',
								'enabled' => false,
								'name' => __('YouTube', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#bb0000',
								'url' => '',
								'order' => 100, 
							),		

			);

			return $defaults;

		}
	} //end class
} //end class test


