<?php

if(!class_exists('HT_Social_Widget_Defaults')){
	class HT_Social_Widget_Defaults {

		/**
		* Get the social media default items
		*/
		public static function get_social_media_defaults(){
			$defaults = array( 

				0 => array( 'provider_id' => 'fa-adn',
								'enabled' => false,
								'name' => __('ADN', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	0, 
							),

				1 => array( 'provider_id' => 'fa-android',
								'enabled' => false,
								'name' => __('Android', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#A4C639',
								'url' => '',
								'order' => 	1, 
							),

				2 => array( 'provider_id' => 'fa-apple',
								'enabled' => false,
								'name' => __('Apple', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#e4e4e5',
								'url' => '',
								'order' => 	2, 
							),

				3 => array( 'provider_id' => 'fa-behance',
								'enabled' => false,
								'name' => __('behance', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#1769ff',
								'url' => '',
								'order' => 	3, 
							),

				4 => array( 'provider_id' => 'fa-behance-square',
								'enabled' => false,
								'name' => __('behance square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#1769ff',
								'url' => '',
								'order' => 	4, 
							),

				5 => array( 'provider_id' => 'fa-bitbucket',
								'enabled' => false,
								'name' => __('Bitbucket', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#205081',
								'url' => '',
								'order' => 	5, 
							),

				6 => array( 'provider_id' => 'fa-bitbucket-square',
								'enabled' => false,
								'name' => __('Bitbucket square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#205081',
								'url' => '',
								'order' => 	6, 
							),


				7 => array( 'provider_id' => 'fa-btc',
								'enabled' => false,
								'name' => __('Bitcoin', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	7, 
							),

				8 => array( 'provider_id' => 'fa-codepen',
								'enabled' => false,
								'name' => __('CodePen', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 	8, 
							),

				9 => array( 'provider_id' => 'fa-css3',
								'enabled' => false,
								'name' => __('CSS3', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 9, 
							),

				10 => array( 'provider_id' => 'fa-delicious',
								'enabled' => false,
								'name' => __('Delicious', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#3399ff',
								'url' => '',
								'order' => 10, 
							),

				11 => array( 'provider_id' => 'fa-deviantart',
								'enabled' => false,
								'name' => __('Deviantart', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#4e6252',
								'url' => '',
								'order' => 11, 
							),

				12 => array( 'provider_id' => 'fa-digg',
								'enabled' => false,
								'name' => __('Digg', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 12, 
							),

				13 => array( 'provider_id' => 'fa-dribbble',
								'enabled' => false,
								'name' => __('Dribble', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#444444',
								'url' => '',
								'order' => 13, 
							),

				14 => array( 'provider_id' => 'fa-dropbox',
								'enabled' => false,
								'name' => __('Dropbox', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#007ee5',
								'url' => '',
								'order' => 14, 
							),

				15 => array( 'provider_id' => 'fa-drupal',
								'enabled' => false,
								'name' => __('Drupal', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0077c0',
								'url' => '',
								'order' => 15, 
							),

				16 => array( 'provider_id' => 'fa-empire',
								'enabled' => false,
								'name' => __('Empire', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 16, 
							),

				17 => array( 'provider_id' => 'fa-facebook',
								'enabled' => false,
								'name' => __('Facebook', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#3b5998',
								'url' => '',
								'order' => 17, 
							),

				18 => array( 'provider_id' => 'fa-facebook-square',
								'enabled' => false,
								'name' => __('Facebook square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#3b5998',
								'url' => '',
								'order' => 18, 
							),

				19 => array( 'provider_id' => 'fa-flickr',
								'enabled' => false,
								'name' => __('Flickr', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0063dc',
								'url' => '',
								'order' => 19, 
							),

				20 => array( 'provider_id' => 'fa-foursquare',
								'enabled' => false,
								'name' => __('FourSquare', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0072b1',
								'url' => '',
								'order' => 20, 
							),


				21 => array( 'provider_id' => 'fa-git',
								'enabled' => false,
								'name' => __('git', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 21, 
							),

				22 => array( 'provider_id' => 'fa-git-square',
								'enabled' => false,
								'name' => __('git square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 22, 
							),

				23 => array( 'provider_id' => 'fa-github',
								'enabled' => false,
								'name' => __('github', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#4183c4',
								'url' => '',
								'order' => 23, 
							),

				24 => array( 'provider_id' => 'fa-github-alt',
								'enabled' => false,
								'name' => __('github alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#4183c4',
								'url' => '',
								'order' => 24, 
							),

				25 => array( 'provider_id' => 'fa-github-square',
								'enabled' => false,
								'name' => __('github square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#4183c4',
								'url' => '',
								'order' => 25, 
							),

				26 => array( 'provider_id' => 'fa-gittip',
								'enabled' => false,
								'name' => __('git tip', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 26, 
							),

				27 => array( 'provider_id' => 'fa-google',
								'enabled' => false,
								'name' => __('Google', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 27, 
							),

				28 => array( 'provider_id' => 'fa-google-plus',
								'enabled' => false,
								'name' => __('Google Plus', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 28, 
							),

				29 => array( 'provider_id' => 'fa-google-plus-square',
								'enabled' => false,
								'name' => __('Google Plus square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#dd4b39',
								'url' => '',
								'order' => 29, 
							),

				30 => array( 'provider_id' => 'fa-hacker-news',
								'enabled' => false,
								'name' => __('Hacker News', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#ff6600',
								'url' => '',
								'order' => 30, 
							),

				31 => array( 'provider_id' => 'fa-html5',
								'enabled' => false,
								'name' => __('HTML5', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#e34f26',
								'url' => '',
								'order' => 31, 
							),

				32 => array( 'provider_id' => 'fa-instagram',
								'enabled' => false,
								'name' => __('Instagram', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#3f729b',
								'url' => '',
								'order' => 32, 
							),

				33 => array( 'provider_id' => 'fa-joomla',
								'enabled' => false,
								'name' => __('Joomla', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 33, 
							),

				34 => array( 'provider_id' => 'fa-jsfiddle',
								'enabled' => false,
								'name' => __('JS Fiddle', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 34, 
							),

				35 => array( 'provider_id' => 'fa-linkedin',
								'enabled' => false,
								'name' => __('LinkedIn', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0976b4',
								'url' => '',
								'order' => 35, 
							),

				36 => array( 'provider_id' => 'fa-linkedin-square',
								'enabled' => false,
								'name' => __('LinkedIn square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#0976b4',
								'url' => '',
								'order' => 36, 
							),

				37 => array( 'provider_id' => 'fa-linux',
								'enabled' => false,
								'name' => __('Linux', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#333333',
								'url' => '',
								'order' => 37, 
							),

				38 => array( 'provider_id' => 'fa-maxcdn',
								'enabled' => false,
								'name' => __('MaxCDN', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#f8711e',
								'url' => '',
								'order' => 38, 
							),

				39 => array( 'provider_id' => 'fa-openid',
								'enabled' => false,
								'name' => __('OpenID', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 39, 
							),

				40 => array( 'provider_id' => 'fa-pagelines',
								'enabled' => false,
								'name' => __('Page Lines', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 40, 
							),

				41 => array( 'provider_id' => 'fa-pied-piper',
								'enabled' => false,
								'name' => __('Pied Piper', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 41, 
							),

				42 => array( 'provider_id' => 'fa-pied-piper-alt',
								'enabled' => false,
								'name' => __('Pied Piper alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 42, 
							),

				43 => array( 'provider_id' => 'fa-pinterest',
								'enabled' => false,
								'name' => __('Pinterest', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#1769ff',
								'url' => '',
								'order' => 43, 
							),

				44 => array( 'provider_id' => 'fa-pinterest-square',
								'enabled' => false,
								'name' => __('Pinterest square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#1769ff',
								'url' => '',
								'order' => 44, 
							),

				45 => array( 'provider_id' => 'fa-qq',
								'enabled' => false,
								'name' => __('QQ', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 45, 
							),


				46 => array( 'provider_id' => 'fa-rebel',
								'enabled' => false,
								'name' => __('Rebel', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#517fa4',
								'url' => '',
								'order' => 46, 
							),

				47 => array( 'provider_id' => 'fa-reddit',
								'enabled' => false,
								'name' => __('Reddit', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#ff4500',
								'url' => '',
								'order' => 47, 
							),

				48 => array( 'provider_id' => 'fa-reddit-square',
								'enabled' => false,
								'name' => __('Reddit square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#ff4500',
								'url' => '',
								'order' => 48, 
							),

				49 => array( 'provider_id' => 'fa-renren',
								'enabled' => false,
								'name' => __('Ren Ren', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#007bb6',
								'url' => '',
								'order' => 49, 
							),

				50 => array( 'provider_id' => 'fa-share-alt',
								'enabled' => false,
								'name' => __('Share alt', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 50, 
							),

				51 => array( 'provider_id' => 'fa-share-alt-square',
								'enabled' => false,
								'name' => __('Share square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 51, 
							),

				52 => array( 'provider_id' => 'fa-skype',
								'enabled' => false,
								'name' => __('Skype', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#00aff0',
								'url' => '',
								'order' => 52, 
							),

				53 => array( 'provider_id' => 'fa-slack',
								'enabled' => false,
								'name' => __('Slack', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 53, 
							),

				54 => array( 'provider_id' => 'fa-soundcloud',
								'enabled' => false,
								'name' => __('Sound Cloud', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#f80',
								'url' => '',
								'order' => 54, 
							),

				55 => array( 'provider_id' => 'fa-spotify',
								'enabled' => false,
								'name' => __('Spotify', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#7ab800',
								'url' => '',
								'order' => 55, 
							),

				56 => array( 'provider_id' => 'fa-stack-exchange',
								'enabled' => false,
								'name' => __('Stack Exchange', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 56, 
							),

				57 => array( 'provider_id' => 'fa-stack-overflow',
								'enabled' => false,
								'name' => __('Stack Overflow', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#fe7a15',
								'url' => '',
								'order' => 57, 
							),

				58 => array( 'provider_id' => 'fa-steam',
								'enabled' => false,
								'name' => __('Steam', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 58, 
							),

				59 => array( 'provider_id' => 'fa-steam-square',
								'enabled' => false,
								'name' => __('Steam square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 59, 
							),

				60 => array( 'provider_id' => 'fa-stumbleupon',
								'enabled' => false,
								'name' => __('Stumble Upon', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#eb4924',
								'url' => '',
								'order' => 60, 
							),

				61 => array( 'provider_id' => 'fa-stumbleupon-circle',
								'enabled' => false,
								'name' => __('Stumble Upon circle', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#eb4924',
								'url' => '',
								'order' => 61, 
							),

				62 => array( 'provider_id' => 'fa-tencent-weibo',
								'enabled' => false,
								'name' => __('Tencent Weibo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 62, 
							),

				63 => array( 'provider_id' => 'fa-trello',
								'enabled' => false,
								'name' => __('Trello', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#256a92',
								'url' => '',
								'order' => 63, 
							),

				64 => array( 'provider_id' => 'fa-tumblr',
								'enabled' => false,
								'name' => __('Tumblr', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#35465c',
								'url' => '',
								'order' => 64, 
							),

				65 => array( 'provider_id' => 'fa-tumblr-square',
								'enabled' => false,
								'name' => __('Tumblr square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#35465c',
								'url' => '',
								'order' => 65, 
							),

				66 => array( 'provider_id' => 'fa-twitter',
								'enabled' => false,
								'name' => __('Twitter', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#55acee',
								'url' => '',
								'order' => 66, 
							),

				67 => array( 'provider_id' => 'fa-twitter-square',
								'enabled' => false,
								'name' => __('Twitter square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#55acee',
								'url' => '',
								'order' => 67, 
							),

				68 => array( 'provider_id' => 'fa-vimeo-square',
								'enabled' => false,
								'name' => __('Vimeo square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#1ab7ea',
								'url' => '',
								'order' => 68, 
							),

				69 => array( 'provider_id' => 'fa-vine',
								'enabled' => false,
								'name' => __('Vine', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#00b488',
								'url' => '',
								'order' => 69, 
							),

				70 => array( 'provider_id' => 'fa-vk',
								'enabled' => false,
								'name' => __('VK', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 70, 
							),

				71 => array( 'provider_id' => 'fa-weibo',
								'enabled' => false,
								'name' => __('Weibo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 71, 
							),

				72 => array( 'provider_id' => 'fa-weixin',
								'enabled' => false,
								'name' => __('Weixin', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#000000',
								'url' => '',
								'order' => 72, 
							),

				73 => array( 'provider_id' => 'fa-windows',
								'enabled' => false,
								'name' => __('Windows', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#00bcf2',
								'url' => '',
								'order' => 73, 
							),

				74 => array( 'provider_id' => 'fa-wordpress',
								'enabled' => false,
								'name' => __('WordPress', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#21759b',
								'url' => '',
								'order' => 74, 
							),

				75 => array( 'provider_id' => 'fa-xing',
								'enabled' => false,
								'name' => __('Xing', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#026466',
								'url' => '',
								'order' => 75, 
							),

				76 => array( 'provider_id' => 'fa-xing-square',
								'enabled' => false,
								'name' => __('Xing square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#026466',
								'url' => '',
								'order' => 76, 
							),

				77 => array( 'provider_id' => 'fa-yahoo',
								'enabled' => false,
								'name' => __('Yahoo', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#400191',
								'url' => '',
								'order' => 77, 
							),

				78 => array( 'provider_id' => 'fa-youtube',
								'enabled' => false,
								'name' => __('YouTube', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#e52d27',
								'url' => '',
								'order' => 78, 
							),

				79 => array( 'provider_id' => 'fa-youtube-play',
								'enabled' => false,
								'name' => __('YouTube play', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#e52d27',
								'url' => '',
								'order' => 79, 
							),

				80 => array( 'provider_id' => 'fa-youtube-square',
								'enabled' => false,
								'name' => __('YouTube square', 'ht-social-widget'),
								'style' => '',
								'background' => '',
								'color' => '#e52d27',
								'url' => '',
								'order' => 80, 
							),
	

			);

			return $defaults;

		}
	} //end class
} //end class test


